In [1]:
list = [1,2,3,4,5,6]

In [2]:
list1 = list.copy()

In [3]:
import numpy as np

In [4]:
list1

[1, 2, 3, 4, 5, 6]

In [5]:
list_array = np.array(list)

In [6]:
list1.pop(1)

2

In [7]:
list1

[1, 3, 4, 5, 6]

In [8]:
list_array

array([1, 2, 3, 4, 5, 6])

In [9]:
list1 = [10,20,2,23,24]

In [10]:
list1_array = np.array(list1)

In [11]:
list2 = [12,14,15,16,48]

In [12]:
list2_array = np.array(list2)

In [13]:
list1_array + list2_array

array([22, 34, 17, 39, 72])

In [14]:
sales = [100,200,300,400,500]

In [15]:
sales_array = np.array(sales)

In [16]:
sales_array

array([100, 200, 300, 400, 500])

In [17]:
profit = [100,200,300,400,500]

In [18]:
profit_array = np.array(profit)

In [19]:
profit_array

array([100, 200, 300, 400, 500])

In [20]:
sales_array/profit_array

array([1., 1., 1., 1., 1.])

In [21]:
list3 = list1.copy()

In [22]:
list3

[10, 20, 2, 23, 24]

In [23]:
del list3

In [24]:
import numpy as np

In [25]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
list(range(0,20))

TypeError: 'list' object is not callable

In [28]:
mydata = np.arange(0,20)

In [29]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
np.reshape(mydata,(5,4),'c')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
np.reshape(mydata,(5,4),'f')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [33]:

mydata = np.reshape(mydata,(5,4),'c')

In [34]:
mydata

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
mydata[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
mydata[0:3,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [37]:
list1[0]='R'

In [38]:
list1

['R', 20, 2, 23, 24]

In [39]:
range1 = [10,20,30,40]
range2 = [40,50,60,70]
range3 = [15,25,35,45]

In [40]:
sales_matrix =np.array([range1,range2,range3])

In [41]:
sales_matrix

array([[10, 20, 30, 40],
       [40, 50, 60, 70],
       [15, 25, 35, 45]])

In [42]:
sales_matrix[0,3]

40

In [43]:
sales_matrix[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [44]:
profit1 = [10,20,30,40]
profit2 = [40,50,60,70]
profit3 = [15,25,35,45]

In [45]:
profit_matrix = np.array([profit1,profit2,profit3])

In [46]:
profit_matrix

array([[10, 20, 30, 40],
       [40, 50, 60, 70],
       [15, 25, 35, 45]])

In [47]:
sales_matrix/profit_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
type(mydata)

numpy.ndarray

In [49]:
mydata1 = np.arange(0,30)

mydata1

In [50]:
mydata1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
np.reshape(mydata1,(6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
mydata1 = np.reshape(mydata1,(6,5))

In [53]:
mydata1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [54]:
mydata1[0,2]

2

In [55]:
mydata1[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [56]:
mydata1[2:5,2:3]

array([[12],
       [17],
       [22]])

In [57]:
North=[1112,1122,1565,1548,1549,1544]
South=[1656,1525,4521,4212,1365,1525]
East=[1562,1552,1615,1552,2654,1455]
West=[1654,1526,1889,1996,1524,1321]

In [58]:
mydata1_matrix = np.array([North,South,East,West])

mydata1_matrix

In [59]:
mydata1_matrix

array([[1112, 1122, 1565, 1548, 1549, 1544],
       [1656, 1525, 4521, 4212, 1365, 1525],
       [1562, 1552, 1615, 1552, 2654, 1455],
       [1654, 1526, 1889, 1996, 1524, 1321]])

In [60]:
mydata1_matrix.T

array([[1112, 1656, 1562, 1654],
       [1122, 1525, 1552, 1526],
       [1565, 4521, 1615, 1889],
       [1548, 4212, 1552, 1996],
       [1549, 1365, 2654, 1524],
       [1544, 1525, 1455, 1321]])

In [61]:
north_sales=[1121,1221,1545,1645]
east_sales=[1548,1879,1996,1354]
west_sales=[1525,2155,1684,1945]

In [62]:
north_profit=[1459,1687,1365,1884]
east_profit=[1652,1995,1388,1347]
west_profit=[1762,1652,1998,1320]

In [63]:
import numpy as np
sales_matrix=np.array([north_sales,east_sales,west_sales])

In [64]:
sales_matrix

array([[1121, 1221, 1545, 1645],
       [1548, 1879, 1996, 1354],
       [1525, 2155, 1684, 1945]])

In [65]:
profit_matrix=np.array([north_profit,east_profit,west_profit])

In [66]:
profit_matrix

array([[1459, 1687, 1365, 1884],
       [1652, 1995, 1388, 1347],
       [1762, 1652, 1998, 1320]])

In [67]:
profit_matrix/sales_matrix

array([[1.3015165 , 1.38165438, 0.88349515, 1.14528875],
       [1.06718346, 1.06173497, 0.69539078, 0.99483013],
       [1.15540984, 0.76658933, 1.18646081, 0.67866324]])

In [68]:
profit_matrix[0,3]

1884

In [69]:
quarter=['Q1','Q2','Q3','Q4']
region=['North','East','West']

In [70]:
quarter_dict={'Q1':0,'Q2':1,'Q3':2,'Q4':3}
region_dict={'North':0,'East':1,'West':2}

In [71]:
profit_matrix[region_dict['North'],quarter_dict['Q4']]

1884

In [72]:
profit_matrix[region_dict['West'],quarter_dict['Q1']]

1762